### ISSUE TITLE
get an Exception when you try to new a tab using 'logger' keyword

### ISSUE THREAD

**Issue by q8247990** [ahawker/crython#23]
when you trying to new a tab like this:
`
Tab=crython.tab.CronTab(name='test',logger=logging.getLogger('xxx'))
`
it throws a Exception.
it is because you try to call the super function ,and thread.__init__() does't accept the keyword logger.
so you should pop the 'logger' keyword out ,the call super function

**Comment by ahawker** [comment]
What are you trying to do by passing a logger to the `CronTab` instance? It already has one and it isn't meant to be overridden.

**Comment by q8247990** [comment]
because i see this code in the __init__() method:

self.logger = kwargs.get('logger') or log.get_logger(__name__)

so I think there is two way to use the log
one is to passing a logger to the CronTab instance, or I should config a
log name CronTab.
I choose the first way,and find out it does't work. So i change the code
like this:

self.logger = kwargs.get('logger') or log.get_logger(__name__)
if kwargs.has_key('logger'):
    kwargs.pop('logger')
super(CronTab, self).__init__(*args, **kwargs)

it works find now

2017-02-07 11:01 GMT+08:00 Andrew Hawker <notifications@github.com>:
