### ISSUE TITLE
Request for updating pypi version to 0.0.8

### ISSUE THREAD

**Issue by samuelnygaard** [ahawker/crython#243]
Hello, we are running crython in production using virtual enviroment, and now we need version 0.0.8 (for the @reboot, annotation), but version 0.0.8 is not available on pypi, and we would prefer not include a manual build for dependencies in our build process.
Is it possible to to upload the newest version of crython to pypi?
https://pypi.org/project/crython/#history

**Comment by ahawker** [comment]
@samuelnygaard Sorry about that! My pypi account had an unverified email address which broke automated tagged deployments. I just fixed it and deployed [Version 0.0.9](https://pypi.org/project/crython/0.0.9/).

**Comment by samuelnygaard** [comment]
Thanks for the quick response.
