### ISSUE TITLE
Does not work in python3.5

### ISSUE THREAD

**Issue by CrabbyPete** [ahawker/crython#31]
Here is the code
`import crython
#Fire every second.
@crython.job(second='*/10')
def foo():
    print ( "I'm Homer Simpson. -- Grimey" )

if __name__ == "__main__":
    crython.start()`

Here is the result
Traceback (most recent call last):
  File "ctest.py", line 3, in <module>
    @crython.job(second='*/10')
  File "/Users/pete/lib/python3.5/site-packages/crython/job.py", line 27, in job
    fields = dict((k, kwargs.pop(k)) for k in kwargs.keys() if k in field.NAMES)
  File "/Users/pete/lib/python3.5/site-packages/crython/job.py", line 27, in <genexpr>
    fields = dict((k, kwargs.pop(k)) for k in kwargs.keys() if k in field.NAMES)
RuntimeError: dictionary changed size during iteration

**Comment by ahawker** [comment]
Sorry about the issue and thanks for reporting it! This should be fixed by https://github.com/ahawker/crython/commit/00e32a23858b2ef46577dc962899646c2770f491

Version `0.0.6` should be available in PyPI with this addressed.

**Comment by CrabbyPete** [comment]
I love the code and look forward to using it
